# Generated by Django 5.2.7 on 2025-11-04 11:47

import apps.core.utils.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for login and notifications",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("MANAGER", "Manager"),
                            ("ADMIN", "Admin"),
                        ],
                        db_index=True,
                        default="EMPLOYEE",
                        help_text="User role for permissions",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee identifier (e.g., EMP001)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                            ("PREFER_NOT_TO_SAY", "Prefer not to say"),
                        ],
                        default="PREFER_NOT_TO_SAY",
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=50)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=20,
                        validators=[apps.core.utils.validators.validate_phone_number],
                    ),
                ),
                ("emergency_contact_name", models.CharField(blank=True, max_length=100)),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[apps.core.utils.validators.validate_phone_number],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[apps.core.utils.validators.validate_postal_code],
                    ),
                ),
                ("country", models.CharField(blank=True, default="Germany", max_length=50)),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, help_text="Date when employee was hired", null=True
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("TERMINATED", "Terminated"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Care Worker, Nurse, Care Manager",
                        max_length=100,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "contract_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Contracted weekly hours",
                        max_digits=5,
                    ),
                ),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("termination_reason", models.TextField(blank=True)),
                (
                    "annual_vacation_days",
                    models.IntegerField(default=30, help_text="Total vacation days per year"),
                ),
                (
                    "remaining_vacation_days",
                    models.IntegerField(
                        default=30, help_text="Remaining vacation days for current year"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hourly rate for hourly employees",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly salary for salaried employees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("notes", models.TextField(blank=True, help_text="Internal HR notes")),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Employee photo",
                        null=True,
                        upload_to="employee_photos/",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User/Employee",
                "verbose_name_plural": "Users/Employees",
                "db_table": "users",
                "ordering": ["employee_id"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
