# Generated by Django 5.2.7 on 2025-11-04 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Employee qualifications and certifications",
                related_name="employees",
                to="employees.qualification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct supervisor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="users_employe_55e465_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employment_status"], name="users_employm_192d1d_idx"),
        ),
    ]
