# Generated by Django 5.2.7 on 2025-11-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employees", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional locations where employee can work",
                related_name="additional_employees",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary work location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_employees",
                to="locations.location",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["primary_location"], name="users_primary_b7b997_idx"),
        ),
    ]
