# Generated by Django 5.2.7 on 2025-11-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_additional_locations_user_primary_location_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_primary_b7b997_idx",
        ),
    ]
