# Generated by Django 5.2.7 on 2025-11-04 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0002_location_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this object has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the object was soft deleted",
                        null=True,
                    ),
                ),
                ("date", models.DateField(db_index=True, help_text="Holiday date")),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., Christmas, New Year)", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Optional description")),
                (
                    "is_nationwide",
                    models.BooleanField(default=True, help_text="True if applies to all locations"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="If true, holiday repeats annually"
                    ),
                ),
                (
                    "recurring_month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        help_text="Month (1-12) for recurring holidays",
                        null=True,
                    ),
                ),
                (
                    "recurring_day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                            (24, 24),
                            (25, 25),
                            (26, 26),
                            (27, 27),
                            (28, 28),
                            (29, 29),
                            (30, 30),
                            (31, 31),
                        ],
                        help_text="Day of month for recurring holidays",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific location, or null for nationwide holiday",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="locations.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Holiday",
                "verbose_name_plural": "Public Holidays",
                "db_table": "public_holidays",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="public_holi_date_5e7351_idx"),
                    models.Index(
                        fields=["location", "date"], name="public_holi_locatio_6caaad_idx"
                    ),
                    models.Index(fields=["is_nationwide"], name="public_holi_is_nati_d713cd_idx"),
                ],
                "unique_together": {("date", "location")},
            },
        ),
        migrations.CreateModel(
            name="VacationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this object has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the object was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, help_text="First day of vacation (inclusive)"),
                ),
                ("end_date", models.DateField(help_text="Last day of vacation (inclusive)")),
                (
                    "vacation_days",
                    models.IntegerField(
                        default=0,
                        help_text="Vacation days (weekdays only, excludes weekends/holidays)",
                    ),
                ),
                ("total_days", models.IntegerField(default=0, help_text="Total calendar days")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL_LEAVE", "Annual Leave"),
                            ("SICK_LEAVE", "Sick Leave"),
                            ("UNPAID_LEAVE", "Unpaid Leave"),
                            ("PARENTAL_LEAVE", "Parental Leave"),
                            ("BEREAVEMENT_LEAVE", "Bereavement Leave"),
                            ("OTHER", "Other"),
                        ],
                        default="ANNUAL_LEAVE",
                        help_text="Type of leave request",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Optional reason for request")),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes (visible to managers)"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        help_text="Supporting document (e.g., medical certificate)",
                        null=True,
                        upload_to="vacation_documents/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was approved", null=True
                    ),
                ),
                (
                    "denied_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was denied", null=True
                    ),
                ),
                ("denial_reason", models.TextField(blank=True, help_text="Reason for denial")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was cancelled", null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who approved this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_vacation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who cancelled this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_vacation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "denied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager who denied this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denied_vacation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee requesting vacation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacation Request",
                "verbose_name_plural": "Vacation Requests",
                "db_table": "vacation_requests",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"], name="vacation_re_employe_5a5df1_idx"
                    ),
                    models.Index(fields=["start_date"], name="vacation_re_start_d_9b1e0e_idx"),
                    models.Index(fields=["status"], name="vacation_re_status_ab1a4f_idx"),
                    models.Index(fields=["approved_by"], name="vacation_re_approve_84367a_idx"),
                ],
            },
        ),
    ]
