# Generated by Django 5.2.7 on 2025-11-13 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this object has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the object was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(help_text="Date when this certification was issued"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when this certification expires (null if non-expiring)",
                        null=True,
                    ),
                ),
                (
                    "certificate_document",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded certificate document (PDF, image, etc.)",
                        null=True,
                        upload_to="certifications/%Y/%m/",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When this certification was verified", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active (Valid and current)"),
                            ("EXPIRING_SOON", "Expiring Soon (Within warning period)"),
                            ("EXPIRED", "Expired (Past expiry date)"),
                            ("PENDING_VERIFICATION", "Pending Verification"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Current status of this certification",
                        max_length=30,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this certification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Certification",
                "verbose_name_plural": "Employee Certifications",
                "db_table": "employee_qualifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="qualification",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
            },
        ),
        migrations.AddField(
            model_name="qualification",
            name="category",
            field=models.CharField(
                choices=[
                    ("MUST_HAVE", "Must Have (Cannot work without)"),
                    ("SPECIALIZED", "Specialized (Required for specific roles)"),
                    ("OPTIONAL", "Optional (Professional development)"),
                ],
                default="OPTIONAL",
                help_text="How critical is this qualification?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="is_required",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this required for employment (affects scheduling)",
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="issuing_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization that issues this qualification (e.g., AHA, Red Cross)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="renewal_period_months",
            field=models.IntegerField(
                blank=True,
                help_text="How often must this be renewed? (e.g., 24 for BLS/ACLS)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique qualification code (e.g., RN, CNA, ACLS, BLS)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of this qualification"
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this qualification still being used/tracked?"
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="name",
            field=models.CharField(help_text="Full name of the qualification", max_length=100),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="required_for_roles",
            field=models.TextField(
                blank=True, help_text='Which roles require this qualification (e.g., "RN, NURSE")'
            ),
        ),
        migrations.AddIndex(
            model_name="qualification",
            index=models.Index(fields=["code"], name="qualificati_code_16a66a_idx"),
        ),
        migrations.AddIndex(
            model_name="qualification",
            index=models.Index(fields=["category"], name="qualificati_categor_1498a2_idx"),
        ),
        migrations.AddIndex(
            model_name="qualification",
            index=models.Index(fields=["is_required"], name="qualificati_is_requ_20f4ff_idx"),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee who holds this certification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="qualification",
            field=models.ForeignKey(
                help_text="Type of qualification/certification",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_certifications",
                to="employees.qualification",
            ),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeequalification",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager/admin who verified this certification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="employeequalification",
            index=models.Index(
                fields=["employee", "status"], name="employee_qu_employe_7f0fff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeequalification",
            index=models.Index(fields=["expiry_date"], name="employee_qu_expiry__015950_idx"),
        ),
        migrations.AddIndex(
            model_name="employeequalification",
            index=models.Index(fields=["status"], name="employee_qu_status_8643df_idx"),
        ),
        migrations.AddIndex(
            model_name="employeequalification",
            index=models.Index(fields=["qualification"], name="employee_qu_qualifi_74a33f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeequalification",
            unique_together={("employee", "qualification", "issue_date")},
        ),
    ]
