# Generated by Django 5.2.7 on 2025-11-04 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_notifications_enabled",
                    models.BooleanField(default=True, help_text="Receive email notifications"),
                ),
                (
                    "push_notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications (future feature)"
                    ),
                ),
                (
                    "vacation_request_submitted",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when vacation request is submitted (managers only)",
                    ),
                ),
                (
                    "vacation_request_approved",
                    models.BooleanField(
                        default=True, help_text="Notify when vacation request is approved"
                    ),
                ),
                (
                    "vacation_request_denied",
                    models.BooleanField(
                        default=True, help_text="Notify when vacation request is denied"
                    ),
                ),
                (
                    "vacation_request_modified",
                    models.BooleanField(
                        default=True, help_text="Notify when vacation request is modified"
                    ),
                ),
                (
                    "vacation_request_cancelled",
                    models.BooleanField(
                        default=True, help_text="Notify when vacation request is cancelled"
                    ),
                ),
                (
                    "shift_assigned",
                    models.BooleanField(default=True, help_text="Notify when shift is assigned"),
                ),
                (
                    "shift_modified",
                    models.BooleanField(default=True, help_text="Notify when shift is modified"),
                ),
                (
                    "profile_updated",
                    models.BooleanField(default=False, help_text="Notify when profile is updated"),
                ),
                (
                    "system_message",
                    models.BooleanField(default=True, help_text="Receive system messages"),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable quiet hours (no notifications)"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, help_text="Start time for quiet hours (e.g., 22:00)", null=True
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="End time for quiet hours (e.g., 07:00)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this object has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the object was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("VACATION_REQUEST_SUBMITTED", "Vacation Request Submitted"),
                            ("VACATION_REQUEST_APPROVED", "Vacation Request Approved"),
                            ("VACATION_REQUEST_DENIED", "Vacation Request Denied"),
                            ("VACATION_REQUEST_MODIFIED", "Vacation Request Modified"),
                            ("VACATION_REQUEST_CANCELLED", "Vacation Request Cancelled"),
                            ("SHIFT_ASSIGNED", "Shift Assigned"),
                            ("SHIFT_MODIFIED", "Shift Modified"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("SYSTEM_MESSAGE", "System Message"),
                        ],
                        db_index=True,
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Notification title/summary", max_length=200)),
                ("message", models.TextField(help_text="Detailed notification message")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Whether notification has been read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was read", null=True
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate to when clicking notification",
                        max_length=500,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="notificatio_recipie_583549_idx"
                    ),
                    models.Index(
                        fields=["notification_type"], name="notificatio_notific_19df93_idx"
                    ),
                    models.Index(fields=["created_at"], name="notificatio_created_e4c995_idx"),
                ],
            },
        ),
    ]
